### PR TITLE
run nbqa-black

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Just an example of how to add nbqa to your workflow - this will apply the `black` autoformatter to your notebooks

----

To be able to merge a pull request, there are a few checks:

TL;DR

[ ] clear title and description to the Pull Request has been provided
[ ] you have read the [Contributing doc](https://github.com/neomatrix369/nlp_profiler/blob/master/CONTRIBUTING.md) and [Developer Guide](https://github.com/neomatrix369/nlp_profiler/blob/master/developer-guide.md)
[ ] the pull request should pass the tests (`./test-coverage "tests slow-tests"``) - this will be visible via the Code coverage report and CI/CD task on the Pull Request
[ ] you have performed some kind of smoke test by running your changes in an isolated environment i.e. Docker container, Google Colab, Kaggle, etc...
[ ] the notebooks are updated (see `notebooks` folder)    
[ ] `CHANGELOG.md` has been updated (please follow the existing format)

## Goal or purpose of the PR

{ Short description outlining what the Pull Request does, and reference the related GitHub issue(s):
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.

## Changes implemented in the PR

{ Please explain what you implemented, why your changes are the best way to achieve the goal(s) above. Also please describe a high-level flow of the implementation and if necessary add some code-level details. If possible provide examples, screen-shots or references to other resources.

This would allow the reviewer to understand your intentions in the code much better.}

### CODE REVIEW

**Comment by neomatrix369** [comment]
Do we need to add `black` and other dependencies to the respective `requirements-*.txt` files? Is this one-off formatting or will it auto-trigger for the notebooks each time?

**Comment by neomatrix369** [comment]
I see this is happening via a GH action. Not via cli, good work! Thanx I'll merge it now

**Comment by neomatrix369** [comment]
I have question, what additional config and docs should I add to the repo for contributors and myself to use `nbqa` locally.

Also is it possible for the pre-commit to run only for changes inside the `notebooks` folder?

**Comment by MarcoGorelli** [comment]
Thanks @neomatrix369 !

If you want to run this locally, all you need to do is:

1. install `pre-commit`: `pip install pre-commit`
2. enable `pre-commit`: `pre-commit install`

then, any time you do a commit, `nbqa-black` will run on the notebooks you've staged. You can also run it manually with
```
pre-commit run --all
```

By default, this hook will only run on Jupyter Notebooks. If you only want to limit it to run on Jupyter Notebooks from `notebooks`, you can add
```
files: ^notebooks/
```
to `.pre-commit-config.yaml`

**Comment by neomatrix369** [comment]
> Thanks @neomatrix369 !
> 
> If you want to run this locally, all you need to do is:
> 
> 1. install `pre-commit`: `pip install pre-commit`
> 2. enable `pre-commit`: `pre-commit install`
> 
> then, any time you do a commit, `nbqa-black` will run on the notebooks you've staged. You can also run it manually with
> 
> ```
> pre-commit run --all
> ```
> 
> By default, this hook will only run on Jupyter Notebooks. If you only want to limit it to run on Jupyter Notebooks from `notebooks`, you can add
> 
> ```
> files: ^notebooks/
> ```
> 
> to `.pre-commit-config.yaml`

Awesome, thanks, the next step is to apply a couple of the code formatting and convention checking plugins to the library i.e. `black` and  <another one>.

**Pull request merged**
